CREATE TABLE `erp_mbti_test_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint DEFAULT NULL COMMENT '用户ID（未登录为NULL）',
  `user_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户姓名',
  `user_phone` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户手机号',
  `user_position` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '岗位',
  `personality_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '性格名称',
  `personality_type` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '性格类型',
  `personality_subtitle` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '性格描述',
  `session_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '会话标识UUID',
  `result_type` char(4) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '测试结果: INTJ/ENFP等',
  `score_e` int NOT NULL DEFAULT '0' COMMENT 'E(外向)得分 0-9',
  `score_i` int NOT NULL DEFAULT '0' COMMENT 'I(内向)得分 0-9',
  `score_s` int NOT NULL DEFAULT '0' COMMENT 'S(实感)得分 0-9',
  `score_n` int NOT NULL DEFAULT '0' COMMENT 'N(直觉)得分 0-9',
  `score_t` int NOT NULL DEFAULT '0' COMMENT 'T(思考)得分 0-9',
  `score_f` int NOT NULL DEFAULT '0' COMMENT 'F(情感)得分 0-9',
  `score_j` int NOT NULL DEFAULT '0' COMMENT 'J(判断)得分 0-9',
  `score_p` int NOT NULL DEFAULT '0' COMMENT 'P(感知)得分 0-9',
  `answers_json` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '完整答案JSON: [{"questionNo":1,"answer":"A"},...]',
  `scores_json` text COLLATE utf8mb4_unicode_ci COMMENT '分析详细JSON',
  `personality_json` text COLLATE utf8mb4_unicode_ci COMMENT '性格详细JSON',
  `duration_seconds` int NOT NULL DEFAULT '0' COMMENT '答题耗时(秒)',
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户IP地址',
  `user_agent` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '浏览器UserAgent',
  `source` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'h5' COMMENT '来源渠道: h5/wechat/app',
  `poster_image` longtext COLLATE utf8mb4_unicode_ci COMMENT '海报图片Base64',
  `status` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '状态（0-启用，1-禁用）',
  `remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `creator` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `updater` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除(0-未删除,1-已删除)',
  `tenant_id` int NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_user_phone` (`user_phone`),
  KEY `idx_result_type` (`result_type`),
  KEY `idx_session_id` (`session_id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MBTI测试记录表';